@echo off
copy %SYSTEMROOT%\System32\msvbvm60.dll .
copy %SYSTEMROOT%\System32\comct232.ocx .
copy %SYSTEMROOT%\System32\comct332.ocx .
copy %SYSTEMROOT%\System32\comctl32.ocx .
copy %SYSTEMROOT%\System32\comdlg32.ocx .
copy %SYSTEMROOT%\System32\dbgrid32.ocx .
copy %SYSTEMROOT%\System32\msadodc.ocx .
copy %SYSTEMROOT%\System32\mschrt20.ocx .
copy %SYSTEMROOT%\System32\mscomct2.ocx .
copy %SYSTEMROOT%\System32\mscomctl.ocx .
copy %SYSTEMROOT%\System32\msdatsrc.tlb .
copy %SYSTEMROOT%\System32\msdxm.ocx .
copy %SYSTEMROOT%\System32\msinet.ocx .
copy %SYSTEMROOT%\System32\mswinsck.ocx .
copy %SYSTEMROOT%\System32\richtx32.ocx .
copy %SYSTEMROOT%\System32\stdole2.tlb .
copy %SYSTEMROOT%\System32\tabctl32.ocx .
copy %SYSTEMROOT%\System32\wmp.ocx .